version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Maintain Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
